### ISSUE TITLE
ESP-IDF 6.0 compatibility: legacy RMT driver removed

### ISSUE THREAD

**Issue by swoboda1337** [Makuna/NeoPixelBus#917]
## Description

NeoPixelBus fails to compile on ESP-IDF 6.0 because `driver/rmt.h` (the legacy RMT driver) has been removed.

```
NeoEsp32RmtMethod.h:49:10: fatal error: driver/rmt.h: No such file or directory
   49 | #include <driver/rmt.h>
```

## Background

In ESP-IDF 6.0, the legacy RMT driver (`driver/rmt.h`) was removed entirely. The replacement is the new RMT driver introduced in IDF 5.0:
- `driver/rmt_tx.h` — transmit channel
- `driver/rmt_encoder.h` — encoding
- `driver/rmt_types.h` — common types

The [ESP-IDF RMT migration guide](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/migration-guides/release-5.x/5.0/peripherals.html#rmt-driver) describes the API changes.

## Affected file

`src/internal/methods/NeoEsp32RmtMethod.h` / `.cpp`

## Environment

- ESP-IDF 6.0.0-rc1
- NeoPixelBus 2.7.3 and 2.8.4
- ESP32 targets

**Comment by swoboda1337** [comment]
I know there is a core3 branch but nothing has happened with that in long time. NeoPixelBus will no longer be usable once IDF 6/Arduino 4 is out.

**Comment by blazoncek** [comment]
Instead of complaining one should provide a patch/PR with a fix and not wait for @Makuna. It will take enough of his time to review and test changes.

Do not forget NeoPixelBus supports platforms other than ESP and if Espressif is constantly changing API then it may not be feasible for a (one man) library to support that (unless users start contributing back to library).

**Comment by swoboda1337** [comment]
The core3 branch has existed for a very long time. It needs to get merged. Not sure what PR would be helpful.

**Comment by blazoncek** [comment]
You can PR to core3 branch.

**Comment by swoboda1337** [comment]
I can open a PR to merge CORE3 into master but that doesnt seem like it would save anyone that much time.

**Comment by blazoncek** [comment]
You are missing the point.
PR proposed changes to core3 branch and then *use* core3 branch after your changes are merged.

**Comment by swoboda1337** [comment]
What changes? Just need CORE3 merged.

**Comment by blazoncek** [comment]
core3 will be merged once it is ready (and also compatible with previous Arduino cores if possible).
Use it as is and report any bug found. If you don't know how to use core3 branch in your projects, please consult your IDE documentation.

**Comment by andrewjswan** [comment]
Branches are used solely for testing, in regular projects, we use stable versions. Therefore, to ensure compatibility with older Arduino, version [2.8.4](https://github.com/Makuna/NeoPixelBus/tree/2.8.4) is available, if desired, it can be maintained and further developed.
However, [CORE3](https://github.com/Makuna/NeoPixelBus/tree/CORE3) needs to either be merged into the `Master` branch or made into a library, for example, version `3.0.0` and then it can be used in projects.

**Comment by swoboda1337** [comment]
Exactly. Unless this is merged soon we decided we will drop support for neopixelbus. There is no choice as the project seems like it is not being maintained.

**Comment by andrewjswan** [comment]
Bad news: the best and most stable library for addressable leds.
