### ISSUE TITLE
NeoPixelBus.h Will Not Compiler (Arduino 2.3.7 for ESP32S3 Dev Module)

### ISSUE THREAD

**Issue by BoCoKeith** [Makuna/NeoPixelBus#915]
**NOTE:  If you are seeking help or have questions, this is NOT the place to do it.**  For questions and support, jump on Gitter and ask away.  
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Makuna/NeoPixelBus?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Describe the bug**
NeoPixelBus.h will not compile using Arduino IDE 2.3.7 targeting "ESP32S3 Dev Module".  The error message is 
```
	In file included from C:\Users\me\OneDrive\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/NeoMethods.h:65,
					 from C:\Users\me\OneDrive\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/NeoPixelBus.h:43,
					 from C:\Users\me\AppData\Local\Temp\.arduinoIDE-unsaved2026123-24652-nuqf6e.f32l\sketch_feb23a\sketch_feb23a.ino:1:
	C:\Users\me\OneDrive\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/methods/NeoEsp32LcdXMethod.h: In member function 'void NeoEsp32LcdMuxBus<T_BUSCONTEXT>::Initialize(uint8_t, uint16_t, bool)':
	C:\Users\me\OneDrive\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/methods/NeoEsp32LcdXMethod.h:545:9: error: there are no arguments to 'gpio_hal_iomux_func_sel' that depend on a template parameter, so a declaration of 'gpio_hal_iomux_func_sel' must be available [-fpermissive]
	  545 |         gpio_hal_iomux_func_sel(GPIO_PIN_MUX_REG[pin], PIN_FUNC_GPIO);
		  |         ^~~~~~~~~~~~~~~~~~~~~~~
	C:\Users\me\OneDrive\Documents\Arduino\libraries\NeoPixelBus_by_Makuna\src/internal/methods/NeoEsp32LcdXMethod.h:545:9: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
	Using library NeoPixelBus by Makuna at version 2.8.4 in folder: C:\Users\me\OneDrive\Documents\Arduino\libraries\NeoPixelBus_by_Makuna 
	Using library SPI at version 3.3.6 in folder: C:\Users\me\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.3.6\libraries\SPI 

```

**To Reproduce**
1. Try to compile "NeoPixelBus.h" from any sketch in Arduino IDE 2.3.7 targeting an "ESP32S3 Dev Module" board.

**Expected behavior**
Successful compilation.

**Development environment (please complete the following information):**
 - OS: Windows 11
 - Build Environment: Arduino IDE 2.3.7
 - Board target: "ESP32S3 Dev Module"
 - Library version: 2.8.4
 - 
**Minimal Sketch that reproduced the problem:**
```
#include "NeoPixelBus.h"

void setup() {
}

void loop() {
}
